---
# tasks file for join-workers
- name:
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - O token {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - O hash é {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: Adicionando o worker ao cluster k8s
  shell: kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash']}} {{K8S_MASTER_NODE_IP}}:{{K8S_API_SECURE_PORT}}
