---
# tasks file for install-helm
- name: Download do Helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh

- name: Modificando as permissões do arquivo de instalação
  command: chmod 700 /tmp/get_helm.sh

- name: Instalando Helm
  shell: /tmp/get_helm.sh

- name: Remove script de instalação
  file:
    path: /tmp/get_helm.sh
    state: absent
